// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsituuspomxaxgmgajcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzaXR1dXNwb214YXhnbWdhamNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDc0ODAsImV4cCI6MjA2NjYyMzQ4MH0.M_44ro9liFdOrV1Dxeq8ONOUBDYQPqmp897D3UP7bkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);